Repository wecode-bootcamp-korea/13-MyFakeTrip-frontend, pull requests merged in 2020-11, with the labels that each got.

#11 [myFakeTrip 서수연] Refactor: 멘토 리뷰 반영
  .gitignore
  .prettierrc.json
  debug.log
  package-lock.json
  package.json
  public/data/hoteldata.json
  public/data/hoteldetaildata.json
  public/data/reviewdata.json
  src/Routes.js
  src/Routes.scss
  src/components/Footer/Footer.component.js
  src/components/Footer/Footer.styles.scss
  src/config.js
  src/index.js
  src/pages/HotelDetails/HotelDetails.component.js
  src/pages/HotelDetails/MainContainer/Head/Head.component.js
  src/pages/HotelDetails/MainContainer/ImageViewer/ImageVeiwer.component.js
  src/pages/HotelDetails/MainContainer/Infos/Facilitis/Facilities.component.js
  src/pages/HotelDetails/MainContainer/Infos/Infos.component.js
  src/pages/HotelDetails/MainContainer/MainContainer.component.js
  src/pages/HotelDetails/MainContainer/Options/Modal/Modal.component.js
  src/pages/HotelDetails/MainContainer/Options/Options.component.js
  src/pages/HotelDetails/MainContainer/Options/People/People.component.js
  src/pages/HotelDetails/MainContainer/Options/Rooms/Rooms.component.js
  src/pages/HotelDetails/MainContainer/Recommend/Recommend.component.js
  src/pages/HotelDetails/MainContainer/Recommend/RecommendCard/RecommendCard.component.js
  src/pages/HotelDetails/MainContainer/Reviews/Review/Review.component.js
  src/pages/HotelDetails/MainContainer/Reviews/Reviews.component.js
  src/pages/HotelDetails/SideBarMain/SideBarMain.component.js
  src/redux/hotels/hotels.actions.js
  src/redux/hotels/hotels.reducer.js
  src/redux/hotels/hotels.types.js
  src/redux/rootReducer.js
  src/redux/store.js
  src/style/reset.scss
Labels: Status: Accepted

#12 [13기 김제형] Modified: 추가적 피드백 적용
  package-lock.json
  package.json
  src/components/AirTicketsAside/AirTicketsAside.component.js
  src/components/AirTicketsAside/AirTicketsAside.styles.js
  src/components/CreditCard/CreditCard.component.js
  src/components/DepartureArrivalContainer/DepartureArrivalContainer.component.js
  src/components/SortedInformation/SortedInformation.styles.js
  src/config.js
  src/redux/airTickets/airTickets.utils.js
Labels: Status: 리뷰 요청

#5 [13기 허덕형] HotelList 레이아웃 구현
  .prettierrc.json
  package-lock.json
  package.json
  public/data/data.json
  src/Routes.js
  src/Routes.scss
  src/config.js
  src/index.js
  src/pages/HotelDetails/HotelDetails.component.js
  src/pages/HotelList/HotelList.component.js
  src/pages/HotelList/HotelList.styles.scss
  src/pages/HotelList/HotelListBar/CountPerson/CountPerson.component.js
  src/pages/HotelList/HotelListBar/HotelListBar.component.js
  src/pages/HotelList/HotelListBar/Region/Region.component.js
  src/pages/HotelList/HotelListMain/HotelListMainLeft/CheckRoomStyle/CheckRoomStyle.component.js
  src/pages/HotelList/HotelListMain/HotelListMainLeft/CheckStarRating/CheckStarRating.component.js
  src/pages/HotelList/HotelListMain/HotelListMainLeft/FilterButton/FilterButton.component.js
  src/pages/HotelList/HotelListMain/HotelListMainLeft/HotelListMainLeft.component.js
  src/pages/HotelList/HotelListMain/HotelListMainRight/HotelListItem.component/HotelListItem.component.js
  src/pages/HotelList/HotelListMain/HotelListMainRight/HotelListMainRight.component.js
  src/pages/HotelList/HotelListMain/WithHotelLoading/HotelLoading/HotelLoading.component.js
  src/pages/HotelList/HotelListMain/WithHotelLoading/LodingBackground.component.js
  src/style/common.scss
  src/theme.js
  yarn.lock
Labels: Status: Conflict 해결 요청

#18 [MyFakeTrip 김지안] Add: Main 페이지 완성
  package-lock.json
  public/data/myrealtrip_logo.png
  src/components/Footer/Footer.styles.scss
  src/components/Nav/Nav.component.js
  src/components/Nav/Nav.styles.scss
  src/components/SearchBar/SearchBar.component.js
  src/components/SearchBar/SearchBar.styles.scss
  src/index.js
  src/pages/AirTickets/AirTickets.styles.scss
  src/pages/Login/Login.component.js
  src/pages/Login/Login.styles.scss
  src/pages/Main/Main.component.js
  src/pages/Main/Main.styles.scss
  src/pages/Main/Select.component.js
  src/pages/Purchase/Purchase.styles.scss
  src/pages/SignUp/SignUp.component.js
  src/pages/SignUp/SignUp.styles.scss
  src/style/common.scss
  src/style/reset.scss
  url.js
Labels: Status: 리뷰 요청

#19 [MyFakeTrip 김지안] Rebase : Login 컴포넌트 완성
  package-lock.json
  package.json
  public/index.html
  src/components/Nav/Nav.component.js
  src/index.js
  src/pages/Login/Login.component.js
  src/pages/Login/Login.styles.scss
  src/pages/Login/LoginEmail.component.js
  src/pages/Main/Main.component.js
  src/pages/Main/Main.styles.scss
  src/pages/SignUp/SignUp.component.js
  src/pages/SignUp/SignUp.styles.scss
  src/redux/rootReducer.js
  src/redux/store.js
  src/redux/user/user.actions.js
  src/redux/user/user.reducer.js
  src/redux/user/user.types.js
Labels: Status: 리뷰 요청

#9 [13기 허덕형] MyPage 레이아웃 구현
  package-lock.json
  package.json
  public/data/data.json
  public/index.html
  src/Routes.js
  src/components/Nav/Nav.component.js
  src/config.js
  src/pages/Login/Login.component.js
  src/pages/MyPage/AirPlaneTicket/AirPlaneTicket.component.js
  src/pages/MyPage/MyPage.component.js
  src/redux/rootReducer.js
  src/redux/store.js
Labels: Status: 리뷰 요청
